title: Rust Network Services Working Group
baseurl: "/team"
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: rust
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
theme: minima
plugins:
  - jekyll-feed
exclude:
  - target # From Rust

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
